In [3]:
import pandas as pd

data = {
    "ProductID": [101, 102, 103, 104, 105, 106],
    "ProductName": [
        "Laptop", 
        "Smartphone", 
        "Desk Chair", 
        "Notebook", 
        "Headphones", 
        "Water Bottle"
    ],
    "Category": [
        "Electronics", 
        "Electronics", 
        "Furniture", 
        "Stationery", 
        "Electronics", 
        "Accessories"
    ],
    "Price": [75000, 30000, 8500, 50, 2500, 300],
    "Stock": [15, 25, 40, 200, 60, 150]
}

df = pd.DataFrame(data)
df

   ProductID   ProductName     Category  Price  Stock
0        101        Laptop  Electronics  75000     15
1        102    Smartphone  Electronics  30000     25
2        103    Desk Chair    Furniture   8500     40
3        104      Notebook   Stationery     50    200
4        105    Headphones  Electronics   2500     60
5        106  Water Bottle  Accessories    300    150

Filter the DataFrame to show only products in the 'Electronics' category.
Sort the filtered DataFrame by price in descending order.

In [4]:
new=df[df["Category"]=="Electronics"]
new

   ProductID ProductName     Category  Price  Stock
0        101      Laptop  Electronics  75000     15
1        102  Smartphone  Electronics  30000     25
4        105  Headphones  Electronics   2500     60

In [12]:
print(new.sort_values("Price", ascending=False))

   ProductID ProductName     Category  Price  Stock
0        101      Laptop  Electronics  75000     15
1        102  Smartphone  Electronics  30000     25
4        105  Headphones  Electronics   2500     60

groupby() on the category column and then use the sum() method on the sales
The final output should show the total sales for each category.

In [14]:
print(df.groupby("Category")["Price"].sum())

Category
Accessories       300
Electronics    107500
Furniture        8500
Stationery         50
Name: Price, dtype: int64

Merge the two DataFrames on the productID column to create a single table that shows each order with the customer's name.

In [16]:
data_customers = {
    "ProductID": [101, 102, 103, 104, 105, 106],
    "CustomerName": [
        "Amelia Johnson",
        "Oliver Smith",
        "Sophia Wilson",
        "Jack Taylor",
        "Isla Brown",
        "Charlie Lewis"
    ]
}

df_customers = pd.DataFrame(data_customers)

print(df_customers)

   ProductID    CustomerName
0        101  Amelia Johnson
1        102    Oliver Smith
2        103   Sophia Wilson
3        104     Jack Taylor
4        105      Isla Brown
5        106   Charlie Lewis

In [28]:
import pandas as pd
new_df =pd.merge(df, df_customers, on="ProductID")
a=new_df.groupby("CustomerName")["ProductName"].apply(list)
a

CustomerName
Amelia Johnson          [Laptop]
Charlie Lewis     [Water Bottle]
Isla Brown          [Headphones]
Jack Taylor           [Notebook]
Oliver Smith        [Smartphone]
Sophia Wilson       [Desk Chair]
Name: ProductName, dtype: object